### ISSUE TITLE
flycheck-plantuml failed to check

### ISSUE THREAD

**Issue by condy0919** [akirak/emacs.d#2]
```
(flycheck-define-checker plantuml
  "A checker using plantuml.

See `http://plantuml.com"
  :command ("java" "-Djava.awt.headless=true" "-jar" (eval plantuml-jar-path) "-syntax")
  :standard-input t
  :error-patterns ((error line-start "ERROR" "\n" line "\n" (message) line-end))
  :modes plantuml-mode)
```
The `plantuml` checker defined by `flycheck-plantuml` uses the jar path.

Sets `plantuml-jar-path` explicitly like that will fix the issue:

```
(use-package flycheck-plantuml
  :ensure t
  :after (flycheck plantuml-mode)
  :config (flycheck-plantuml-setup)
  ;; flycheck-plantuml only support the jar style
  :custom (plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar"))
```

**Comment by akirak** [comment]
Thanks, I didn't know there was a person who was actually trying to use my config.

I install most external dependencies using Nix via [home-manager](https://github.com/akirak/home.nix). I also save machine-specific configuration in `custom-file`. You can change the value of the variable with `M-x customize-variable RET plantuml-jar-path`.
